import { useMemo, useState, type FormEvent } from "react";
import { signup, type User } from "../api";
import { IconAlert, IconSpinner } from "../components/Icons";

interface SignupPageProps { onSignup: (user: User, token: string) => void; onSignIn: () => void; }
const ROLES = [["technician", "Technician"], ["maintenance_supervisor", "Maintenance Supervisor"], ["production_supervisor", "Production Supervisor"], ["plant_manager", "Plant Manager"]] as const;

export function SignupPage({ onSignup, onSignIn }: SignupPageProps) {
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [confirm, setConfirm] = useState(""); const [role, setRole] = useState("technician"); const [loading, setLoading] = useState(false); const [error, setError] = useState<string | null>(null);
  const strength = useMemo(() => password.length >= 12 ? "Strong" : password.length >= 8 ? "Good" : "Use at least 8 characters", [password]);
  async function submit(event: FormEvent) { event.preventDefault(); setError(null); if (!/^\S+@\S+\.\S+$/.test(email)) return setError("Enter a valid email address."); if (password !== confirm) return setError("Passwords do not match."); setLoading(true); try { const result = await signup(email.trim(), password, role); onSignup(result.user, result.token); } catch { setError("Could not create account. That email may already be registered."); } finally { setLoading(false); } }
  return <div className="login-page animate-fade"><div className="login-card animate-scale"><div className="login-logo">AM<span>&</span>POP</div><p className="login-tagline">Create your secure workspace account.</p><form onSubmit={submit} className="login-form">{error && <div className="login-error"><IconAlert size={16} /><span>{error}</span></div>}<div className="login-field"><label htmlFor="signup-email">Email</label><input id="signup-email" type="email" value={email} onChange={(e) => setEmail(e.target.value)} required /></div><div className="login-field"><label htmlFor="signup-role">Role</label><select id="signup-role" className="form-select" value={role} onChange={(e) => setRole(e.target.value)}>{ROLES.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></div><div className="login-field"><label htmlFor="signup-password">Password</label><input id="signup-password" type="password" minLength={8} value={password} onChange={(e) => setPassword(e.target.value)} required /><small className="text-muted">Password strength: {strength}</small></div><div className="login-field"><label htmlFor="signup-confirm">Confirm password</label><input id="signup-confirm" type="password" minLength={8} value={confirm} onChange={(e) => setConfirm(e.target.value)} required /></div><button type="submit" className="login-btn" disabled={loading}>{loading ? <><IconSpinner size={16} /> Creating account…</> : "Create account"}</button></form><p className="text-muted" style={{ textAlign: "center", marginTop: "18px" }}>Already have an account? <button type="button" className="btn-link" onClick={onSignIn}>Sign in</button></p></div></div>;
}
